version: '3.8'

services:
  clisp-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clispconnect_web
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://clisp_user:clisp_pass@clisp-db:5432/clisp_db?schema=public
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=
    depends_on:
      - clisp-db
      - clisp-cache

  clisp-db:
    image: postgis/postgis:15-3.3-alpine
    container_name: clispconnect_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clisp_user
      - POSTGRES_PASSWORD=clisp_pass
      - POSTGRES_DB=clisp_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  clisp-cache:
    image: redis:7-alpine
    container_name: clispconnect_cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
